package com.github.joonasvali.demo.tools;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.tool.annotation.Tool;
import org.springframework.stereotype.Component;

@Component
public class RandomTopicTools {
  private static final Logger logger = LoggerFactory.getLogger(RandomNumberTools.class);

  @Tool(name = "generateRandomTopic", description = "Generates a random topic for any purpose.")
  public String generateRandomTopic() {
    int index = (int) (Math.random() * TOPICS.length);
    logger.info("Generated random topic: {}", TOPICS[index]);
    return TOPICS[index];
  }

  private static final String[] TOPICS = {
      "Technology",
      "Science",
      "History",
      "Art",
      "Music",
      "Sports",
      "Travel",
      "Food",
      "Movies",
      "Books",
      "Rabbits",
      "Cats",
      "Dogs",
      "Space",
      "Nature",
      "Philosophy",
      "Psychology",
      "Education",
      "Health",
      "Environment",
      "Baking",
      "Gardening",
      "Photography",
      "Fashion",
      "Gaming",
      "Fitness",
      "Cooking",
      "Hiking",
      "Dancing",
      "Writing",
      "Crafts",
      "Meditation",
      "Yoga",
      "Fishing",
      "Birdwatching",
      "Robotics",
      "AI",
      "Blockchain",
      "Cryptocurrency",
      "Virtual Reality",
      "Augmented Reality",
      "3D Printing",
      "Renewable Energy",
      "Climate Change",
      "Marine Biology",
      "Astronomy",
      "Geology",
      "Meteorology",
      "Archaeology",
      "Linguistics",
      "Sociology",
      "Anthropology",
      "Economics",
      "Political Science",
      "Law",
      "Medicine",
      "Nursing",
      "Pharmacy",
      "Dentistry",
      "Veterinary Science",
      "Architecture",
      "Urban Planning",
      "Interior Design",
      "Graphic Design",
      "Web Development",
      "App Development",
      "Data Science",
      "Machine Learning",
      "Cybersecurity",
      "Networking",
      "Cloud Computing",
      "DevOps",
      "Project Management",
      "Agile Methodologies",
      "Scrum",
      "Limited Edition Sneakers",
      "Streetwear Fashion",
      "Indie Music Scenes",
      "Underground Art Movements",
      "Esports Tournaments",
      "DIY Home Improvement",
      "Sustainable Living",
      "Tiny House Movement",
      "Urban Gardening",
      "Food Truck Culture",
      "Craft Beer Brewing",
      "Wine Tasting",
      "Whiskey Distilling",
      "Travel Hacking",
      "Backpacking Adventures",
      "Culinary Arts",
      "World Cuisines",
      "Film Festivals",
      "Classic Literature",
      "Contemporary Fiction",
      "Poetry",
      "Graphic Novels",
      "Stand-up Comedy",
      "Improv Theater",
      "Magic and Illusions",
      "Board Games",
      "Role-playing Games",
      "Card Games",
      "Puzzles and Brain Teasers",
      "Model Building",
      "Collecting Antiques",
      "Genealogy",
      "Astrology",
      "Tarot Reading",
      "Numerology",
      "Mythology",
      "Folklore",
      "Conspiracy Theories",
      "Paranormal Phenomena",
      "Cryptozoology",
      "Urban Legends",
      "Survival Skills",
      "First Aid",
      "Emergency Preparedness",
      "Self-defense",
      "Martial Arts",
      "Yoga and Mindfulness",
      "Pilates",
      "Tai Chi",
      "Zumba",
      "CrossFit",
      "Marathons and Running",
      "Cycling",
      "Swimming",
      "Triathlons",
      "Rock Climbing",
      "Skiing and Snowboarding",
      "Surfing",
      "Scuba Diving",
      "Sailing",
      "Motorcycling",
      "Car Restoration",
      "Photography Techniques",
      "Photo Editing",
      "Videography",
      "Film Production",
      "Animation",
      "Graphic Design Software",
      "3D Modeling",
      "UI/UX Design",
      "Digital Marketing",
      "The Office",
      "Parks and Recreation",
      "Stranger Things",
      "Game of Thrones",
      "Breaking Bad",
      "The Mandalorian",
      "The Witcher",
      "Black Mirror",
      "The Crown",
      "Sherlock",
      "Friends",
      "How I Met Your Mother",
      "Rick and Morty",
      "BoJack Horseman",
      "Avatar: The Last Airbender",
      "The Legend of Korra",
      "Dragon Ball Z",
      "Naruto",
      "One Piece",
      "Attack on Titan",
      "My Hero Academia",
      "Demon Slayer",
      "Jujutsu Kaisen",
      "Fullmetal Alchemist",
      "Death Note",
      "Tokyo Ghoul",
      "Bleach",
      "Fairy Tail",
      "Sword Art Online",
      "Black Clover",
  };

}
